### ISSUE TITLE
Nuxt API not accessable

### ISSUE THREAD

**Issue by allestaire** [nevadskiy/laravel-nuxt-docker#29]
Still cant get it to working,
![image](https://user-images.githubusercontent.com/68372409/128298991-ebfd0a3b-521a-4e9a-a795-dea03b27f82b.png)
already tried `nginx:80` or `nginx:81` as proxy address but still cant connect to laravel api.
~~but when I enter to `frontend` nuxt container and run `wget nginx:80/api` the container is connected to it and the file was downloaded~~. Sorry my but, the response was the nuxt document was downloaded instead of json
![image](https://user-images.githubusercontent.com/68372409/128299501-3b62bf98-83ed-48c8-bb76-03b9cf1ce598.png)

heres the NGINX Configuration
```
# Nuxt Configuration

server {
    listen          80;             # the port nginx is listening on
    # server_name     your-domain;    # setup your domain here

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    charset utf-8;
    

    gzip            on;
    gzip_types      text/plain application/xml text/css application/javascript;
    gzip_min_length 1000;

    location / {
        # expires $expires;

        proxy_redirect                      off;
        proxy_set_header Host               $host;
        proxy_set_header X-Real-IP          $remote_addr;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  $scheme;
        proxy_read_timeout          1m;
        proxy_connect_timeout       1m;
        proxy_pass                          http://frontend:3000; # set the address of the Node.js instance here
    }
    # Proxy all API requests
    location ~ ^/(api|storage)/ {
        proxy_pass http://nginx:81;
        proxy_set_header Host $http_host;
    }
}


## Laravel Configurations
server {
    listen 81;
    index index.php index.html;
    root /var/www/public;
    client_max_body_size 32M;
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_read_timeout 300;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
    location ~ /\.(?!well-known).* {
        deny all;
    }
}
```

Docker compose on nuxt and nginx
```
nginx:
    build:
      context: ./.Docker/nginx
    volumes_from:
      - app
    ports:
      - 4000:80
      - 4001:81
    networks:
      - app-network
    depends_on:
      - frontend
      - app
...

frontend:
    build:
      context: ./
      dockerfile: ./.Docker/nuxt/Dockerfile
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/.nuxt
    networks:
      - app-network
```
