### ISSUE TITLE
mysql instead of postgres

### ISSUE THREAD

**Issue by kevinosburn** [nevadskiy/laravel-nuxt-docker#7]
Hi @nevadskiy 

This is very useful... Thanks for putting this together!

Not an "issue", but more of a feature request. What would be the best approach to replace postgres with mysql?

Thanks!

**Comment by xalaida** [comment]
Hi @kevinosburn. 

You're welcome :wink:!

1. Replace `postgres` and `postgres-testing` sections in the `docker-compose.yml` file with the following code:
```
  ### MySQL Database ##########################
  mysql:
    image: mysql:5.7
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_DATABASE=app
    ports:
      - 33061:3306
```

2. Remove current docker volumes with postgres data running the following command:
```
docker-compose down --volumes
```

3. Remove docker/postgres directory.

4. Replace all `postgres` occurrences in the `docker-compose.yml` with `mysql`.

5. Update your .env database configuration:
```
DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
```

6. Add the following code to `docker/php-cli/Dockerfile`, `docker/php-fpm/Dockerfile` and `docker/supervisor/Dockerfile` files replacing `# Postgres` line:
```
# MySQL
RUN docker-php-ext-install pdo pdo_mysql
```

7. Run `docker-compose build` command, then `docker-compose restart`.

That should work. 

And one question from me, please. Which OS do you use?

**Comment by kevinosburn** [comment]
Hi @nevadskiy 

Thanks for the fast response!

I'm running this on Ubuntu 18.04 and also on a Windows 10 machine.

Oh, just a small typo here... `istall` should be `install`

Install composer dependencies:
`docker-compose exec php-cli composer istall`

-Kevin

**Comment by xalaida** [comment]
@kevinosburn thanks.

**Comment by DmitrySkibitsky** [comment]
@nevadskiy 
Good afternoon. For some reason, I can't connect to MySQL with under Laravel.
Tell me what could be the problem?

Error
```log
make migrate
docker-compose exec php php artisan migrate

   Illuminate\Database\QueryException 

  SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client (SQL: select * from information_schema.tables where table_schema = laravel_base and table_name = migrations and table_type = 'BASE TABLE')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:671
    667▕         // If an exception occurs when attempting to run a query, we'll format the error
    668▕         // message to include the bindings with SQL, which will make this exception a
    669▕         // lot more helpful to the developer instead of just the database's errors.
    670▕         catch (Exception $e) {
  ➜ 671▕             throw new QueryException(
    672▕                 $query, $this->prepareBindings($bindings), $e
    673▕             );
    674▕         }
    675▕ 

      +34 vendor frames 
  35  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

env data
![2020-09-26_19-02](https://user-images.githubusercontent.com/20288556/94344847-d9584800-002a-11eb-893d-a67899d80a50.png)

make status
![2020-09-26_18-59](https://user-images.githubusercontent.com/20288556/94344822-9b5b2400-002a-11eb-855b-68a29e580556.png)

docker-compose.yml
```yml
mysql:
    image: mysql:latest
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASE=laravel_base
    ports:
      - 33061:3306
```

I also tried to run the application on MySQL 5.7
I modified the docker-compose file and rebuild it.
```yml
mysql:
    image: mysql:5.7
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASE=laravel_base
    ports:
      - 33061:3306
```
But on this version my MySQL service does not start. I was looking for what could be the problem and advised to switch to latest

![2020-09-26_19-12](https://user-images.githubusercontent.com/20288556/94345105-50daa700-002c-11eb-9f8a-fc84b5e5615d.png)
